name: Morning practice

on:
 push:
   branches:
     - main
     - develop

jobs:
  inspect-project:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v6
      - name: Welcome
        run: echo " Iam learning CI step by step"
      - name: Inspect project
        run: |
          pwd
          ls
          cat requirements.txt
