name: First 

on:
 push:
   branches:
     - main
jobs:
  practice:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo "I am learning GitHub Actions"
      - name: Finish practice
        run: echo "My second step is running"
      - name: Show information
        run: |
          echo "Checking the runner"
          pwd
          ls
