name: Morning practice

on:
 push:
   branches:
     - main
     - develop

jobs:
  inspect-project:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v6
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: check-python-version
        run: python --version
      - name: Welcome
        run: echo " Iam learning CI step by step"
      - name: Inspect project
        run: |
          pwd
          ls
          cat requirements.txt
      - name: install dependencies
        run: python -m pip install -r requirements.txt
